//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.20506.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Net.BITS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Net.BITS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \s*(\w+)\s*,\s*&quot;(\w*)&quot;,\s*&quot;([0-9a-fA-F]{40})&quot;\s*,\s*&quot;(\w*)&quot;\s*,\s*(True|False).
        /// </summary>
        internal static string ClientCertificateRegex {
            get {
                return ResourceManager.GetString("ClientCertificateRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, &quot;{1}&quot;, &quot;{2}&quot;, &quot;{3}&quot;, {4}.
        /// </summary>
        internal static string ClientCertificateToStringFormat {
            get {
                return ResourceManager.GetString("ClientCertificateToStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is already a member of a collection.
        /// </summary>
        internal static string FileInCollection {
            get {
                return ResourceManager.GetString("FileInCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \s*(\d+)\s*,\s*(\d+).
        /// </summary>
        internal static string FileRangeRegex {
            get {
                return ResourceManager.GetString("FileRangeRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1}.
        /// </summary>
        internal static string FileRangeToStringFormat {
            get {
                return ResourceManager.GetString("FileRangeToStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File : {{&quot;{0}&quot;,&quot;{1}&quot;}}.
        /// </summary>
        internal static string FileToStringFormat {
            get {
                return ResourceManager.GetString("FileToStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; is already in the collection.
        /// </summary>
        internal static string FileUniqueFormat {
            get {
                return ResourceManager.GetString("FileUniqueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The job is already a member of a collection.
        /// </summary>
        internal static string JobInCollection {
            get {
                return ResourceManager.GetString("JobInCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The job must be in a collection and Resume must be called before you can use this method or property.
        /// </summary>
        internal static string JobInvalid {
            get {
                return ResourceManager.GetString("JobInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \s*(\w+)\s*,\s*&quot;(\w*)&quot;\s*,\s*&quot;(\w*)&quot;.
        /// </summary>
        internal static string JobProxySettingsRegEx {
            get {
                return ResourceManager.GetString("JobProxySettingsRegEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, &quot;{1}&quot;, &quot;{2}&quot;.
        /// </summary>
        internal static string JobProxySettingsToStringFormat {
            get {
                return ResourceManager.GetString("JobProxySettingsToStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job : {{&quot;{0}&quot;,&quot;{1}&quot;}}.
        /// </summary>
        internal static string JobToStringFormat {
            get {
                return ResourceManager.GetString("JobToStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BITS is not installed on this machine.
        /// </summary>
        internal static string NoBITS {
            get {
                return ResourceManager.GetString("NoBITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \s*&quot;([^*?&quot;&lt;&gt;|]*)&quot;\s*,\s*&quot;([^*?&quot;&lt;&gt;|]*)&quot;.
        /// </summary>
        internal static string NotifyCmdLineRegex {
            get {
                return ResourceManager.GetString("NotifyCmdLineRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot;, &quot;{1}&quot;.
        /// </summary>
        internal static string NotifyCmdLineToStringFormat {
            get {
                return ResourceManager.GetString("NotifyCmdLineToStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This method can not be called once Job.Resume has been called.
        /// </summary>
        internal static string PreResumeMethod {
            get {
                return ResourceManager.GetString("PreResumeMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This property can not be changed once Job.Resume has been called.
        /// </summary>
        internal static string PreResumeProperty {
            get {
                return ResourceManager.GetString("PreResumeProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The feature is unsupported by this version of BITS.
        /// </summary>
        internal static string Unsupported {
            get {
                return ResourceManager.GetString("Unsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\{1}.
        /// </summary>
        internal static string UserNameFormat {
            get {
                return ResourceManager.GetString("UserNameFormat", resourceCulture);
            }
        }
    }
}
