//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevenUpdate.Service
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.ObjectModel;
    using System.Diagnostics;
    using System.ServiceModel;
    using System.ServiceModel.Channels;

    using Microsoft.Win32;

    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [ServiceContract(ConfigurationName = "Service.IService", CallbackContract = typeof(IServiceCallback), SessionMode = SessionMode.Required)]
    public interface IService
    {
        [OperationContract(IsOneWay = true, Action = "http://tempuri.org/IService/AddApp")]
        void AddApp(Sua application);

        [OperationContract(IsOneWay = true, Action = "http://tempuri.org/IService/ChangeSettings")]
        void ChangeSettings(Collection<Sua> applications, Config options, bool autoCheck);

        [OperationContract(IsOneWay = true, Action = "http://tempuri.org/IService/HideUpdate")]
        void HideUpdate(Suh hiddenUpdate);

        [OperationContract(IsOneWay = true, Action = "http://tempuri.org/IService/HideUpdates")]
        void HideUpdates(Collection<Suh> hiddenUpdates);

        [OperationContract(IsOneWay = true, Action = "http://tempuri.org/IService/InstallUpdates")]
        void InstallUpdates(Collection<Sui> appUpdates);

        [OperationContract(IsOneWay = true, Action = "http://tempuri.org/IService/ShowUpdate")]
        void ShowUpdate(Suh hiddenUpdate);

        [OperationContract(IsOneWay = true, Action = "http://tempuri.org/IService/Subscribe")]
        void Subscribe();

        [OperationContract(IsOneWay = true, Action = "http://tempuri.org/IService/Unsubscribe")]
        void Unsubscribe();
    }

    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public interface IServiceCallback
    {
        [OperationContract(IsOneWay = true, Action = "http://tempuri.org/IService/OnDownloadCompleted")]
        [ServiceKnownType(typeof(EventArgs))]
        [ServiceKnownType(typeof(RegistryValueKind))]
        [ServiceKnownType(typeof(RegistryHive))]
        [ServiceKnownType(typeof(Sua))]
        [ServiceKnownType(typeof(Collection<LocaleString>))]
        [ServiceKnownType(typeof(LocaleString))]
        [ServiceKnownType(typeof(Collection<Sua>))]
        [ServiceKnownType(typeof(Config))]
        [ServiceKnownType(typeof(AutoUpdateOption))]
        [ServiceKnownType(typeof(Suh))]
        [ServiceKnownType(typeof(Importance))]
        [ServiceKnownType(typeof(UpdateStatus))]
        [ServiceKnownType(typeof(Collection<Suh>))]
        [ServiceKnownType(typeof(Collection<Sui>))]
        [ServiceKnownType(typeof(Sui))]
        [ServiceKnownType(typeof(Collection<Update>))]
        [ServiceKnownType(typeof(Update))]
        [ServiceKnownType(typeof(Collection<UpdateFile>))]
        [ServiceKnownType(typeof(UpdateFile))]
        [ServiceKnownType(typeof(FileAction))]
        [ServiceKnownType(typeof(Collection<RegistryItem>))]
        [ServiceKnownType(typeof(RegistryItem))]
        [ServiceKnownType(typeof(RegistryAction))]
        [ServiceKnownType(typeof(Collection<Shortcut>))]
        [ServiceKnownType(typeof(Shortcut))]
        [ServiceKnownType(typeof(ShortcutAction))]
        [ServiceKnownType(typeof(DownloadCompletedEventArgs))]
        [ServiceKnownType(typeof(DownloadProgressChangedEventArgs))]
        [ServiceKnownType(typeof(ErrorOccurredEventArgs))]
        [ServiceKnownType(typeof(InstallCompletedEventArgs))]
        [ServiceKnownType(typeof(InstallProgressChangedEventArgs))]
        void OnDownloadCompleted(object sender, DownloadCompletedEventArgs e);

        [OperationContract(IsOneWay = true, Action = "http://tempuri.org/IService/OnDownloadProgressChanged")]
        [ServiceKnownType(typeof(EventArgs))]
        [ServiceKnownType(typeof(RegistryValueKind))]
        [ServiceKnownType(typeof(RegistryHive))]
        [ServiceKnownType(typeof(Sua))]
        [ServiceKnownType(typeof(Collection<LocaleString>))]
        [ServiceKnownType(typeof(LocaleString))]
        [ServiceKnownType(typeof(Collection<Sua>))]
        [ServiceKnownType(typeof(Config))]
        [ServiceKnownType(typeof(AutoUpdateOption))]
        [ServiceKnownType(typeof(Suh))]
        [ServiceKnownType(typeof(Importance))]
        [ServiceKnownType(typeof(UpdateStatus))]
        [ServiceKnownType(typeof(Collection<Suh>))]
        [ServiceKnownType(typeof(Collection<Sui>))]
        [ServiceKnownType(typeof(Sui))]
        [ServiceKnownType(typeof(Collection<Update>))]
        [ServiceKnownType(typeof(Update))]
        [ServiceKnownType(typeof(Collection<UpdateFile>))]
        [ServiceKnownType(typeof(UpdateFile))]
        [ServiceKnownType(typeof(FileAction))]
        [ServiceKnownType(typeof(Collection<RegistryItem>))]
        [ServiceKnownType(typeof(RegistryItem))]
        [ServiceKnownType(typeof(RegistryAction))]
        [ServiceKnownType(typeof(Collection<Shortcut>))]
        [ServiceKnownType(typeof(Shortcut))]
        [ServiceKnownType(typeof(ShortcutAction))]
        [ServiceKnownType(typeof(DownloadCompletedEventArgs))]
        [ServiceKnownType(typeof(DownloadProgressChangedEventArgs))]
        [ServiceKnownType(typeof(ErrorOccurredEventArgs))]
        [ServiceKnownType(typeof(InstallCompletedEventArgs))]
        [ServiceKnownType(typeof(InstallProgressChangedEventArgs))]
        void OnDownloadProgressChanged(object sender, DownloadProgressChangedEventArgs e);

        [OperationContract(IsOneWay = true, Action = "http://tempuri.org/IService/OnErrorOccurred")]
        [ServiceKnownType(typeof(EventArgs))]
        [ServiceKnownType(typeof(RegistryValueKind))]
        [ServiceKnownType(typeof(RegistryHive))]
        [ServiceKnownType(typeof(Sua))]
        [ServiceKnownType(typeof(Collection<LocaleString>))]
        [ServiceKnownType(typeof(LocaleString))]
        [ServiceKnownType(typeof(Collection<Sua>))]
        [ServiceKnownType(typeof(Config))]
        [ServiceKnownType(typeof(AutoUpdateOption))]
        [ServiceKnownType(typeof(Suh))]
        [ServiceKnownType(typeof(Importance))]
        [ServiceKnownType(typeof(UpdateStatus))]
        [ServiceKnownType(typeof(Collection<Suh>))]
        [ServiceKnownType(typeof(Collection<Sui>))]
        [ServiceKnownType(typeof(Sui))]
        [ServiceKnownType(typeof(Collection<Update>))]
        [ServiceKnownType(typeof(Update))]
        [ServiceKnownType(typeof(Collection<UpdateFile>))]
        [ServiceKnownType(typeof(UpdateFile))]
        [ServiceKnownType(typeof(FileAction))]
        [ServiceKnownType(typeof(Collection<RegistryItem>))]
        [ServiceKnownType(typeof(RegistryItem))]
        [ServiceKnownType(typeof(RegistryAction))]
        [ServiceKnownType(typeof(Collection<Shortcut>))]
        [ServiceKnownType(typeof(Shortcut))]
        [ServiceKnownType(typeof(ShortcutAction))]
        [ServiceKnownType(typeof(DownloadCompletedEventArgs))]
        [ServiceKnownType(typeof(DownloadProgressChangedEventArgs))]
        [ServiceKnownType(typeof(ErrorOccurredEventArgs))]
        [ServiceKnownType(typeof(InstallCompletedEventArgs))]
        [ServiceKnownType(typeof(InstallProgressChangedEventArgs))]
        void OnErrorOccurred(object sender, ErrorOccurredEventArgs e);

        [OperationContract(IsOneWay = true, Action = "http://tempuri.org/IService/OnInstallCompleted")]
        [ServiceKnownType(typeof(EventArgs))]
        [ServiceKnownType(typeof(RegistryValueKind))]
        [ServiceKnownType(typeof(RegistryHive))]
        [ServiceKnownType(typeof(Sua))]
        [ServiceKnownType(typeof(Collection<LocaleString>))]
        [ServiceKnownType(typeof(LocaleString))]
        [ServiceKnownType(typeof(Collection<Sua>))]
        [ServiceKnownType(typeof(Config))]
        [ServiceKnownType(typeof(AutoUpdateOption))]
        [ServiceKnownType(typeof(Suh))]
        [ServiceKnownType(typeof(Importance))]
        [ServiceKnownType(typeof(UpdateStatus))]
        [ServiceKnownType(typeof(Collection<Suh>))]
        [ServiceKnownType(typeof(Collection<Sui>))]
        [ServiceKnownType(typeof(Sui))]
        [ServiceKnownType(typeof(Collection<Update>))]
        [ServiceKnownType(typeof(Update))]
        [ServiceKnownType(typeof(Collection<UpdateFile>))]
        [ServiceKnownType(typeof(UpdateFile))]
        [ServiceKnownType(typeof(FileAction))]
        [ServiceKnownType(typeof(Collection<RegistryItem>))]
        [ServiceKnownType(typeof(RegistryItem))]
        [ServiceKnownType(typeof(RegistryAction))]
        [ServiceKnownType(typeof(Collection<Shortcut>))]
        [ServiceKnownType(typeof(Shortcut))]
        [ServiceKnownType(typeof(ShortcutAction))]
        [ServiceKnownType(typeof(DownloadCompletedEventArgs))]
        [ServiceKnownType(typeof(DownloadProgressChangedEventArgs))]
        [ServiceKnownType(typeof(ErrorOccurredEventArgs))]
        [ServiceKnownType(typeof(InstallCompletedEventArgs))]
        [ServiceKnownType(typeof(InstallProgressChangedEventArgs))]
        void OnInstallCompleted(object sender, InstallCompletedEventArgs e);

        [OperationContract(IsOneWay = true, Action = "http://tempuri.org/IService/OnInstallProgressChanged")]
        [ServiceKnownType(typeof(EventArgs))]
        [ServiceKnownType(typeof(RegistryValueKind))]
        [ServiceKnownType(typeof(RegistryHive))]
        [ServiceKnownType(typeof(Sua))]
        [ServiceKnownType(typeof(Collection<LocaleString>))]
        [ServiceKnownType(typeof(LocaleString))]
        [ServiceKnownType(typeof(Collection<Sua>))]
        [ServiceKnownType(typeof(Config))]
        [ServiceKnownType(typeof(AutoUpdateOption))]
        [ServiceKnownType(typeof(Suh))]
        [ServiceKnownType(typeof(Importance))]
        [ServiceKnownType(typeof(UpdateStatus))]
        [ServiceKnownType(typeof(Collection<Suh>))]
        [ServiceKnownType(typeof(Collection<Sui>))]
        [ServiceKnownType(typeof(Sui))]
        [ServiceKnownType(typeof(Collection<Update>))]
        [ServiceKnownType(typeof(Update))]
        [ServiceKnownType(typeof(Collection<UpdateFile>))]
        [ServiceKnownType(typeof(UpdateFile))]
        [ServiceKnownType(typeof(FileAction))]
        [ServiceKnownType(typeof(Collection<RegistryItem>))]
        [ServiceKnownType(typeof(RegistryItem))]
        [ServiceKnownType(typeof(RegistryAction))]
        [ServiceKnownType(typeof(Collection<Shortcut>))]
        [ServiceKnownType(typeof(Shortcut))]
        [ServiceKnownType(typeof(ShortcutAction))]
        [ServiceKnownType(typeof(DownloadCompletedEventArgs))]
        [ServiceKnownType(typeof(DownloadProgressChangedEventArgs))]
        [ServiceKnownType(typeof(ErrorOccurredEventArgs))]
        [ServiceKnownType(typeof(InstallCompletedEventArgs))]
        [ServiceKnownType(typeof(InstallProgressChangedEventArgs))]
        void OnInstallProgressChanged(object sender, InstallProgressChangedEventArgs e);
    }

    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : IService, IClientChannel
    {
    }

    [DebuggerStepThrough]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public class ServiceClient : DuplexClientBase<IService>, IService
    {
        public ServiceClient(InstanceContext callbackInstance) : base(callbackInstance)
        {
        }

        public ServiceClient(InstanceContext callbackInstance, string endpointConfigurationName) : base(callbackInstance, endpointConfigurationName)
        {
        }

        public ServiceClient(InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : base(callbackInstance, endpointConfigurationName, remoteAddress)
        {
        }

        public ServiceClient(InstanceContext callbackInstance, string endpointConfigurationName, EndpointAddress remoteAddress) : base(callbackInstance, endpointConfigurationName, remoteAddress)
        {
        }

        public ServiceClient(InstanceContext callbackInstance, Binding binding, EndpointAddress remoteAddress) : base(callbackInstance, binding, remoteAddress)
        {
        }

        public void AddApp(Sua application)
        {
            base.Channel.AddApp(application);
        }

        public void ChangeSettings(Collection<Sua> applications, Config options, bool autoCheck)
        {
            base.Channel.ChangeSettings(applications, options, autoCheck);
        }

        public void HideUpdate(Suh hiddenUpdate)
        {
            base.Channel.HideUpdate(hiddenUpdate);
        }

        public void HideUpdates(Collection<Suh> hiddenUpdates)
        {
            base.Channel.HideUpdates(hiddenUpdates);
        }

        public void InstallUpdates(Collection<Sui> appUpdates)
        {
            base.Channel.InstallUpdates(appUpdates);
        }

        public void ShowUpdate(Suh hiddenUpdate)
        {
            base.Channel.ShowUpdate(hiddenUpdate);
        }

        public void Subscribe()
        {
            base.Channel.Subscribe();
        }

        public void Unsubscribe()
        {
            base.Channel.Unsubscribe();
        }
    }
}