//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevenUpdate.Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service.IService", CallbackContract=typeof(SevenUpdate.Service.IServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService/AddApp")]
        void AddApp(SevenUpdate.Sua application);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService/ChangeSettings")]
        void ChangeSettings(System.Collections.ObjectModel.Collection<SevenUpdate.Sua> applications, SevenUpdate.Config options, bool autoCheck);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService/HideUpdate")]
        void HideUpdate(SevenUpdate.Suh hiddenUpdate);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService/HideUpdates")]
        void HideUpdates(System.Collections.ObjectModel.Collection<SevenUpdate.Suh> hiddenUpdates);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService/InstallUpdates")]
        void InstallUpdates(System.Collections.ObjectModel.Collection<SevenUpdate.Sui> appUpdates);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService/ShowUpdate")]
        void ShowUpdate(SevenUpdate.Suh hiddenUpdate);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService/Subscribe")]
        void Subscribe();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService/Unsubscribe")]
        void Unsubscribe();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService/OnDownloadCompleted")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.EventArgs))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Microsoft.Win32.RegistryValueKind))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Microsoft.Win32.RegistryHive))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.Sua))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<SevenUpdate.LocaleString>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.LocaleString))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<SevenUpdate.Sua>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.Config))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.AutoUpdateOption))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.Suh))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.Importance))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.UpdateStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<SevenUpdate.Suh>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<SevenUpdate.Sui>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.Sui))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<SevenUpdate.Update>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.Update))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<SevenUpdate.UpdateFile>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.UpdateFile))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.FileAction))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<SevenUpdate.RegistryItem>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.RegistryItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.RegistryAction))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<SevenUpdate.Shortcut>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.Shortcut))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.ShortcutAction))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.DownloadCompletedEventArgs))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.DownloadProgressChangedEventArgs))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.ErrorOccurredEventArgs))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.InstallCompletedEventArgs))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.InstallProgressChangedEventArgs))]
        void OnDownloadCompleted(object sender, SevenUpdate.DownloadCompletedEventArgs e);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService/OnDownloadProgressChanged")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.EventArgs))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Microsoft.Win32.RegistryValueKind))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Microsoft.Win32.RegistryHive))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.Sua))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<SevenUpdate.LocaleString>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.LocaleString))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<SevenUpdate.Sua>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.Config))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.AutoUpdateOption))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.Suh))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.Importance))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.UpdateStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<SevenUpdate.Suh>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<SevenUpdate.Sui>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.Sui))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<SevenUpdate.Update>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.Update))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<SevenUpdate.UpdateFile>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.UpdateFile))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.FileAction))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<SevenUpdate.RegistryItem>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.RegistryItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.RegistryAction))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<SevenUpdate.Shortcut>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.Shortcut))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.ShortcutAction))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.DownloadCompletedEventArgs))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.DownloadProgressChangedEventArgs))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.ErrorOccurredEventArgs))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.InstallCompletedEventArgs))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.InstallProgressChangedEventArgs))]
        void OnDownloadProgressChanged(object sender, SevenUpdate.DownloadProgressChangedEventArgs e);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService/OnErrorOccurred")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.EventArgs))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Microsoft.Win32.RegistryValueKind))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Microsoft.Win32.RegistryHive))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.Sua))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<SevenUpdate.LocaleString>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.LocaleString))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<SevenUpdate.Sua>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.Config))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.AutoUpdateOption))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.Suh))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.Importance))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.UpdateStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<SevenUpdate.Suh>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<SevenUpdate.Sui>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.Sui))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<SevenUpdate.Update>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.Update))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<SevenUpdate.UpdateFile>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.UpdateFile))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.FileAction))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<SevenUpdate.RegistryItem>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.RegistryItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.RegistryAction))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<SevenUpdate.Shortcut>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.Shortcut))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.ShortcutAction))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.DownloadCompletedEventArgs))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.DownloadProgressChangedEventArgs))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.ErrorOccurredEventArgs))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.InstallCompletedEventArgs))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.InstallProgressChangedEventArgs))]
        void OnErrorOccurred(object sender, SevenUpdate.ErrorOccurredEventArgs e);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService/OnInstallCompleted")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.EventArgs))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Microsoft.Win32.RegistryValueKind))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Microsoft.Win32.RegistryHive))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.Sua))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<SevenUpdate.LocaleString>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.LocaleString))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<SevenUpdate.Sua>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.Config))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.AutoUpdateOption))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.Suh))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.Importance))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.UpdateStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<SevenUpdate.Suh>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<SevenUpdate.Sui>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.Sui))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<SevenUpdate.Update>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.Update))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<SevenUpdate.UpdateFile>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.UpdateFile))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.FileAction))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<SevenUpdate.RegistryItem>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.RegistryItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.RegistryAction))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<SevenUpdate.Shortcut>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.Shortcut))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.ShortcutAction))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.DownloadCompletedEventArgs))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.DownloadProgressChangedEventArgs))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.ErrorOccurredEventArgs))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.InstallCompletedEventArgs))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.InstallProgressChangedEventArgs))]
        void OnInstallCompleted(object sender, SevenUpdate.InstallCompletedEventArgs e);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService/OnInstallProgressChanged")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.EventArgs))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Microsoft.Win32.RegistryValueKind))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Microsoft.Win32.RegistryHive))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.Sua))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<SevenUpdate.LocaleString>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.LocaleString))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<SevenUpdate.Sua>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.Config))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.AutoUpdateOption))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.Suh))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.Importance))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.UpdateStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<SevenUpdate.Suh>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<SevenUpdate.Sui>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.Sui))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<SevenUpdate.Update>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.Update))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<SevenUpdate.UpdateFile>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.UpdateFile))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.FileAction))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<SevenUpdate.RegistryItem>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.RegistryItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.RegistryAction))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<SevenUpdate.Shortcut>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.Shortcut))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.ShortcutAction))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.DownloadCompletedEventArgs))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.DownloadProgressChangedEventArgs))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.ErrorOccurredEventArgs))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.InstallCompletedEventArgs))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SevenUpdate.InstallProgressChangedEventArgs))]
        void OnInstallProgressChanged(object sender, SevenUpdate.InstallProgressChangedEventArgs e);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : SevenUpdate.Service.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.DuplexClientBase<SevenUpdate.Service.IService>, SevenUpdate.Service.IService {
        
        public ServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void AddApp(SevenUpdate.Sua application) {
            base.Channel.AddApp(application);
        }
        
        public void ChangeSettings(System.Collections.ObjectModel.Collection<SevenUpdate.Sua> applications, SevenUpdate.Config options, bool autoCheck) {
            base.Channel.ChangeSettings(applications, options, autoCheck);
        }
        
        public void HideUpdate(SevenUpdate.Suh hiddenUpdate) {
            base.Channel.HideUpdate(hiddenUpdate);
        }
        
        public void HideUpdates(System.Collections.ObjectModel.Collection<SevenUpdate.Suh> hiddenUpdates) {
            base.Channel.HideUpdates(hiddenUpdates);
        }
        
        public void InstallUpdates(System.Collections.ObjectModel.Collection<SevenUpdate.Sui> appUpdates) {
            base.Channel.InstallUpdates(appUpdates);
        }
        
        public void ShowUpdate(SevenUpdate.Suh hiddenUpdate) {
            base.Channel.ShowUpdate(hiddenUpdate);
        }
        
        public void Subscribe() {
            base.Channel.Subscribe();
        }
        
        public void Unsubscribe() {
            base.Channel.Unsubscribe();
        }
    }
}
