//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.21006.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevenUpdate.Sdk {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UIStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SevenUpdate.Sdk.UIStrings", typeof(UIStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must calculate an updated SHA1 Hash for the current file.
        /// </summary>
        internal static string CalculateHash {
            get {
                return ResourceManager.GetString("CalculateHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate Hash &amp; Size.
        /// </summary>
        internal static string CalculateHashSize {
            get {
                return ResourceManager.GetString("CalculateHashSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose an update name!.
        /// </summary>
        internal static string ChooseUpdateName {
            get {
                return ResourceManager.GetString("ChooseUpdateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load.
        /// </summary>
        internal static string CouldNotLoad {
            get {
                return ResourceManager.GetString("CouldNotLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t show me this message again..
        /// </summary>
        internal static string DontShowMessage {
            get {
                return ResourceManager.GetString("DontShowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter the file size in bytes for the current file.
        /// </summary>
        internal static string EnterFileSize {
            get {
                return ResourceManager.GetString("EnterFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you would like to exit?.
        /// </summary>
        internal static string ExitConfirm {
            get {
                return ResourceManager.GetString("ExitConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expanded Path.
        /// </summary>
        internal static string ExpandedPath {
            get {
                return ResourceManager.GetString("ExpandedPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file name you have entered contains an invalid character:.
        /// </summary>
        internal static string FileNameInvalid {
            get {
                return ResourceManager.GetString("FileNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before you can continue please fill in the required information.
        /// </summary>
        internal static string FillRequiredInformation {
            get {
                return ResourceManager.GetString("FillRequiredInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you exit now you will lose unsaved progress..
        /// </summary>
        internal static string LoseProgress {
            get {
                return ResourceManager.GetString("LoseProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New File.
        /// </summary>
        internal static string NewFile {
            get {
                return ResourceManager.GetString("NewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Registry Item.
        /// </summary>
        internal static string NewRegistryItem {
            get {
                return ResourceManager.GetString("NewRegistryItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Shortcut.
        /// </summary>
        internal static string NewShortcut {
            get {
                return ResourceManager.GetString("NewShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory path you have entered contains an invalid character:.
        /// </summary>
        internal static string PathInvalid {
            get {
                return ResourceManager.GetString("PathInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry Item.
        /// </summary>
        internal static string RegistryItem {
            get {
                return ResourceManager.GetString("RegistryItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please save the current item or remove it to continue.
        /// </summary>
        internal static string SaveItemOrRemoveIt {
            get {
                return ResourceManager.GetString("SaveItemOrRemoveIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seven Software.
        /// </summary>
        internal static string SevenSoftware {
            get {
                return ResourceManager.GetString("SevenSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut.
        /// </summary>
        internal static string Shortcut {
            get {
                return ResourceManager.GetString("Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path you provided for the shortcut is not valid..
        /// </summary>
        internal static string ShortcutNotValid {
            get {
                return ResourceManager.GetString("ShortcutNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SUI is not valid or has been corrupted..
        /// </summary>
        internal static string SuiInvalid {
            get {
                return ResourceManager.GetString("SuiInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The url you have entered is not valid..
        /// </summary>
        internal static string UrlNotValid {
            get {
                return ResourceManager.GetString("UrlNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The url you have entered must point to your sui file..
        /// </summary>
        internal static string UrlSui {
            get {
                return ResourceManager.GetString("UrlSui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The url you have entered is valid..
        /// </summary>
        internal static string UrlValid {
            get {
                return ResourceManager.GetString("UrlValid", resourceCulture);
            }
        }
    }
}
