//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevenUpdate.Sdk.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SevenUpdate.Sdk.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Seven Update SDK.
        /// </summary>
        public static string AboutSevenUpdateSDK {
            get {
                return ResourceManager.GetString("AboutSevenUpdateSDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add File(s).
        /// </summary>
        public static string AddFiles {
            get {
                return ResourceManager.GetString("AddFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Folder.
        /// </summary>
        public static string AddFolder {
            get {
                return ResourceManager.GetString("AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Update.
        /// </summary>
        public static string AddOrUpdate {
            get {
                return ResourceManager.GetString("AddOrUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates or updates the shortcut.
        /// </summary>
        public static string AddOrUpdateToolTip {
            get {
                return ResourceManager.GetString("AddOrUpdateToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Registry Item.
        /// </summary>
        public static string AddRegistryItem {
            get {
                return ResourceManager.GetString("AddRegistryItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Shortcut.
        /// </summary>
        public static string AddShortcut {
            get {
                return ResourceManager.GetString("AddShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds a new update to {0}.
        /// </summary>
        public static string AddUpdate {
            get {
                return ResourceManager.GetString("AddUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        public static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apache License 2.0.
        /// </summary>
        public static string ApacheLicense {
            get {
                return ResourceManager.GetString("ApacheLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft® Windows® API Code Pack is licensed under the.
        /// </summary>
        public static string ApiCodePackLicense {
            get {
                return ResourceManager.GetString("ApiCodePackLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robert Baker (sevenalive) - Creator and Lead Developer.
        /// </summary>
        public static string AppCreator {
            get {
                return ResourceManager.GetString("AppCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application description:.
        /// </summary>
        public static string ApplicationDescription {
            get {
                return ResourceManager.GetString("ApplicationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a summary about the application here, but make it no longer than 300 characters.
        /// </summary>
        public static string ApplicationDescriptionNote {
            get {
                return ResourceManager.GetString("ApplicationDescriptionNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application install location:.
        /// </summary>
        public static string ApplicationInstallLocation {
            get {
                return ResourceManager.GetString("ApplicationInstallLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory where the application is is installed. It is best to use system path variabes when applicable..
        /// </summary>
        public static string ApplicationInstallLocationToolTip {
            get {
                return ResourceManager.GetString("ApplicationInstallLocationToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application name:.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seven Update SDK (max 100 characters).
        /// </summary>
        public static string ApplicationNameNote {
            get {
                return ResourceManager.GetString("ApplicationNameNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the application to be updated..
        /// </summary>
        public static string ApplicationNameToolTip {
            get {
                return ResourceManager.GetString("ApplicationNameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application web site:.
        /// </summary>
        public static string ApplicationWebsite {
            get {
                return ResourceManager.GetString("ApplicationWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A url pointing to the web site of the publisher or the software..
        /// </summary>
        public static string ApplicationWebsiteToolTip {
            get {
                return ResourceManager.GetString("ApplicationWebsiteToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        public static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Optional) Enter command line arguments to be passed when file is executed during update.
        /// </summary>
        public static string ArgumentNote {
            get {
                return ResourceManager.GetString("ArgumentNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bengali.
        /// </summary>
        public static string Bengali {
            get {
                return ResourceManager.GetString("Bengali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary.
        /// </summary>
        public static string Binary {
            get {
                return ResourceManager.GetString("Binary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BSD license.
        /// </summary>
        public static string BSDlicense {
            get {
                return ResourceManager.GetString("BSDlicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating hash....
        /// </summary>
        public static string CalculatingHash {
            get {
                return ResourceManager.GetString("CalculatingHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command args:.
        /// </summary>
        public static string CommandArgs {
            get {
                return ResourceManager.GetString("CommandArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter any arguments to be executed with the file.
        /// </summary>
        public static string CommandArgsToolTip {
            get {
                return ResourceManager.GetString("CommandArgsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare only.
        /// </summary>
        public static string CompareOnly {
            get {
                return ResourceManager.GetString("CompareOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix all errors to continue.
        /// </summary>
        public static string CorrectErrors {
            get {
                return ResourceManager.GetString("CorrectErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new project.
        /// </summary>
        public static string CreateNewProject {
            get {
                return ResourceManager.GetString("CreateNewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new update.
        /// </summary>
        public static string CreateNewUpdate {
            get {
                return ResourceManager.GetString("CreateNewUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new project.
        /// </summary>
        public static string CreateProject {
            get {
                return ResourceManager.GetString("CreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Seven Update to update your software.
        /// </summary>
        public static string CreateProjectNote {
            get {
                return ResourceManager.GetString("CreateProjectNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new update.
        /// </summary>
        public static string CreateUpdate {
            get {
                return ResourceManager.GetString("CreateUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete key.
        /// </summary>
        public static string DeleteKey {
            get {
                return ResourceManager.GetString("DeleteKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete shortcut.
        /// </summary>
        public static string DeleteShortcut {
            get {
                return ResourceManager.GetString("DeleteShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes the shortcut on the system.
        /// </summary>
        public static string DeleteShortcutToolTip {
            get {
                return ResourceManager.GetString("DeleteShortcutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete value.
        /// </summary>
        public static string DeleteValue {
            get {
                return ResourceManager.GetString("DeleteValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development Team:.
        /// </summary>
        public static string DevelopmentTeam {
            get {
                return ResourceManager.GetString("DevelopmentTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Optional) An absolute url that will download the file (file must have public read access).
        /// </summary>
        public static string DownloadLocationNote {
            get {
                return ResourceManager.GetString("DownloadLocationNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download location:.
        /// </summary>
        public static string DownloadUrl {
            get {
                return ResourceManager.GetString("DownloadUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch.
        /// </summary>
        public static string Dutch {
            get {
                return ResourceManager.GetString("Dutch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DWord.
        /// </summary>
        public static string DWord {
            get {
                return ResourceManager.GetString("DWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit {0}.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute.
        /// </summary>
        public static string Execute {
            get {
                return ResourceManager.GetString("Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute &amp; delete.
        /// </summary>
        public static string ExecuteDelete {
            get {
                return ResourceManager.GetString("ExecuteDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpandString.
        /// </summary>
        public static string ExpandString {
            get {
                return ResourceManager.GetString("ExpandString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exports the files needed to release your update(s).
        /// </summary>
        public static string ExportProjectNote {
            get {
                return ResourceManager.GetString("ExportProjectNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File action:.
        /// </summary>
        public static string FileAction {
            get {
                return ResourceManager.GetString("FileAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The action to take on this file.
        /// </summary>
        public static string FileActionToolTip {
            get {
                return ResourceManager.GetString("FileActionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path entered is not valid..
        /// </summary>
        public static string FilePathInvalid {
            get {
                return ResourceManager.GetString("FilePathInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File System.
        /// </summary>
        public static string FileSystem {
            get {
                return ResourceManager.GetString("FileSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To get started, right click the list box and create or import a registry item.
        /// </summary>
        public static string GetStartedRegistry {
            get {
                return ResourceManager.GetString("GetStartedRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To get started, right click the list box and create or import a shortcut.
        /// </summary>
        public static string GetStartedShortcut {
            get {
                return ResourceManager.GetString("GetStartedShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help &amp; Support.
        /// </summary>
        public static string HelpSupport {
            get {
                return ResourceManager.GetString("HelpSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help &amp; Support web site:.
        /// </summary>
        public static string HelpWebsite {
            get {
                return ResourceManager.GetString("HelpWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A url pointing to the support area for this software..
        /// </summary>
        public static string HelpWebsiteToolTip {
            get {
                return ResourceManager.GetString("HelpWebsiteToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hindi.
        /// </summary>
        public static string Hindi {
            get {
                return ResourceManager.GetString("Hindi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important.
        /// </summary>
        public static string Important {
            get {
                return ResourceManager.GetString("Important", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Registry File.
        /// </summary>
        public static string ImportRegistryFile {
            get {
                return ResourceManager.GetString("ImportRegistryFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Shortcut.
        /// </summary>
        public static string ImportShortcut {
            get {
                return ResourceManager.GetString("ImportShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value is required for this field..
        /// </summary>
        public static string InputRequired {
            get {
                return ResourceManager.GetString("InputRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install location:.
        /// </summary>
        public static string InstallLocation {
            get {
                return ResourceManager.GetString("InstallLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An absolute Uri pointing to the installed location of the file on a system.
        /// </summary>
        public static string InstallLocationNote {
            get {
                return ResourceManager.GetString("InstallLocationNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard windows variables are allowed ex. %USERNAME%. Use %INSTALLDIR% for files in the app directory and %DOWNLOADURL% for files in the download directory.
        /// </summary>
        public static string InstallLocationToolTip {
            get {
                return ResourceManager.GetString("InstallLocationToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 64-bit application.
        /// </summary>
        public static string Is64Bit {
            get {
                return ResourceManager.GetString("Is64Bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check this box if your software is native x64..
        /// </summary>
        public static string Is64BitToolTip {
            get {
                return ResourceManager.GetString("Is64BitToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese.
        /// </summary>
        public static string Japanese {
            get {
                return ResourceManager.GetString("Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key path:.
        /// </summary>
        public static string KeyPath {
            get {
                return ResourceManager.GetString("KeyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The full key path where the value containing the install location of the application is stored. Acceptable hive formats: HKLM\Software or HKEY_LOCAL_MACHINE.
        /// </summary>
        public static string KeyPathToolTip {
            get {
                return ResourceManager.GetString("KeyPathToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Optional) http://www.gnu.org/licenses/gpl-3.0.txt (Must point to readable file).
        /// </summary>
        public static string LicenseUrlNote {
            get {
                return ResourceManager.GetString("LicenseUrlNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locale.
        /// </summary>
        public static string Locale {
            get {
                return ResourceManager.GetString("Locale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to locate the application directory.
        /// </summary>
        public static string LocateAppDirectory {
            get {
                return ResourceManager.GetString("LocateAppDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to locate the file location.
        /// </summary>
        public static string LocateFileLocation {
            get {
                return ResourceManager.GetString("LocateFileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Software License.
        /// </summary>
        public static string MicrosoftLicense {
            get {
                return ResourceManager.GetString("MicrosoftLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Public License.
        /// </summary>
        public static string MicrosoftPublicLicense {
            get {
                return ResourceManager.GetString("MicrosoftPublicLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MultiString.
        /// </summary>
        public static string MultiString {
            get {
                return ResourceManager.GetString("MultiString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Shortcut.
        /// </summary>
        public static string MyShortcut {
            get {
                return ResourceManager.GetString("MyShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Registry Item.
        /// </summary>
        public static string NewRegistryItem {
            get {
                return ResourceManager.GetString("NewRegistryItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Shortcut.
        /// </summary>
        public static string NewShortcut {
            get {
                return ResourceManager.GetString("NewShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional.
        /// </summary>
        public static string Optional {
            get {
                return ResourceManager.GetString("Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish.
        /// </summary>
        public static string Polish {
            get {
                return ResourceManager.GetString("Polish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portions of code use the following libraries:.
        /// </summary>
        public static string PortionsOfCode {
            get {
                return ResourceManager.GetString("PortionsOfCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese.
        /// </summary>
        public static string Portuguese {
            get {
                return ResourceManager.GetString("Portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error loading the project..
        /// </summary>
        public static string ProjectLoadError {
            get {
                return ResourceManager.GetString("ProjectLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to protobuf-net is licensed under the.
        /// </summary>
        public static string protobufLicense {
            get {
                return ResourceManager.GetString("protobufLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher information.
        /// </summary>
        public static string PublisherInformation {
            get {
                return ResourceManager.GetString("PublisherInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher name:.
        /// </summary>
        public static string PublisherName {
            get {
                return ResourceManager.GetString("PublisherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QWord.
        /// </summary>
        public static string QWord {
            get {
                return ResourceManager.GetString("QWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent projects.
        /// </summary>
        public static string RecentProjects {
            get {
                return ResourceManager.GetString("RecentProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended.
        /// </summary>
        public static string Recommended {
            get {
                return ResourceManager.GetString("Recommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry file.
        /// </summary>
        public static string RegFile {
            get {
                return ResourceManager.GetString("RegFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry.
        /// </summary>
        public static string Registry {
            get {
                return ResourceManager.GetString("Registry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry Action.
        /// </summary>
        public static string RegistryAction {
            get {
                return ResourceManager.GetString("RegistryAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry Item.
        /// </summary>
        public static string RegistryItem {
            get {
                return ResourceManager.GetString("RegistryItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry key:.
        /// </summary>
        public static string RegistryKey {
            get {
                return ResourceManager.GetString("RegistryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry.
        /// </summary>
        public static string RegistryTitle {
            get {
                return ResourceManager.GetString("RegistryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Location.
        /// </summary>
        public static string RegistryValueNote {
            get {
                return ResourceManager.GetString("RegistryValueNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release application.
        /// </summary>
        public static string ReleaseApplication {
            get {
                return ResourceManager.GetString("ReleaseApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release date:.
        /// </summary>
        public static string ReleaseDate {
            get {
                return ResourceManager.GetString("ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date the update was released to the public..
        /// </summary>
        public static string ReleaseDateToolTip {
            get {
                return ResourceManager.GetString("ReleaseDateToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release updates.
        /// </summary>
        public static string ReleaseUpdates {
            get {
                return ResourceManager.GetString("ReleaseUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove All Files.
        /// </summary>
        public static string RemoveAllFiles {
            get {
                return ResourceManager.GetString("RemoveAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove All Registry Items.
        /// </summary>
        public static string RemoveAllRegistryItems {
            get {
                return ResourceManager.GetString("RemoveAllRegistryItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove All Shortcuts.
        /// </summary>
        public static string RemoveAllShortcuts {
            get {
                return ResourceManager.GetString("RemoveAllShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove File.
        /// </summary>
        public static string RemoveFile {
            get {
                return ResourceManager.GetString("RemoveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Registry Item.
        /// </summary>
        public static string RemoveRegistryItem {
            get {
                return ResourceManager.GetString("RemoveRegistryItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Shortcut.
        /// </summary>
        public static string RemoveShortcut {
            get {
                return ResourceManager.GetString("RemoveShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        public static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        public static string Russian {
            get {
                return ResourceManager.GetString("Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save project.
        /// </summary>
        public static string SaveProject {
            get {
                return ResourceManager.GetString("SaveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save project and release updates.
        /// </summary>
        public static string SaveProjectRelease {
            get {
                return ResourceManager.GetString("SaveProjectRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seven Software.
        /// </summary>
        public static string SevenSoftware {
            get {
                return ResourceManager.GetString("SevenSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seven Update SDK is licensed under the GNU GPL 3.0 © 2007-2010.
        /// </summary>
        public static string SevenUpdateLicense {
            get {
                return ResourceManager.GetString("SevenUpdateLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seven Update SDK.
        /// </summary>
        public static string SevenUpdateSDK {
            get {
                return ResourceManager.GetString("SevenUpdateSDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHA-2 hash:.
        /// </summary>
        public static string SHA2Hash {
            get {
                return ResourceManager.GetString("SHA2Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to update the hash, it must be correct for the file for Seven Update to work properly.
        /// </summary>
        public static string SHA2HashToolTip {
            get {
                return ResourceManager.GetString("SHA2HashToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharpBITS.NET is licensed under the.
        /// </summary>
        public static string SharpBitsLicense {
            get {
                return ResourceManager.GetString("SharpBitsLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut.
        /// </summary>
        public static string Shortcut {
            get {
                return ResourceManager.GetString("Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut Action.
        /// </summary>
        public static string ShortcutAction {
            get {
                return ResourceManager.GetString("ShortcutAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command line arguments for the shortcut.
        /// </summary>
        public static string ShortcutArguementsToolTip {
            get {
                return ResourceManager.GetString("ShortcutArguementsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut arguments:.
        /// </summary>
        public static string ShortcutArguments {
            get {
                return ResourceManager.GetString("ShortcutArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut description:.
        /// </summary>
        public static string ShortcutDescription {
            get {
                return ResourceManager.GetString("ShortcutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Optional) Displays a description of the shortcut on mouse hover.
        /// </summary>
        public static string ShortcutDescriptionNote {
            get {
                return ResourceManager.GetString("ShortcutDescriptionNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A simple description of the target exe.
        /// </summary>
        public static string ShortcutDescriptionToolTip {
            get {
                return ResourceManager.GetString("ShortcutDescriptionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut icon:.
        /// </summary>
        public static string ShortcutIcon {
            get {
                return ResourceManager.GetString("ShortcutIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A path pointing to an ico to use as the shortcut icon.
        /// </summary>
        public static string ShortcutIconToolTip {
            get {
                return ResourceManager.GetString("ShortcutIconToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut name:.
        /// </summary>
        public static string ShortcutName {
            get {
                return ResourceManager.GetString("ShortcutName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcuts.
        /// </summary>
        public static string Shortcuts {
            get {
                return ResourceManager.GetString("Shortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut save location:.
        /// </summary>
        public static string ShortcutSaveLocation {
            get {
                return ResourceManager.GetString("ShortcutSaveLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location where the shortcut resides, example: startmenu or desktop.
        /// </summary>
        public static string ShortcutSaveLocationToolTip {
            get {
                return ResourceManager.GetString("ShortcutSaveLocationToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut target:.
        /// </summary>
        public static string ShortcutTarget {
            get {
                return ResourceManager.GetString("ShortcutTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app or path the shortcut points to.
        /// </summary>
        public static string ShortcutTargetToolTip {
            get {
                return ResourceManager.GetString("ShortcutTargetToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the shortcut.
        /// </summary>
        public static string ShortcutToolTip {
            get {
                return ResourceManager.GetString("ShortcutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The software company or development team..
        /// </summary>
        public static string SoftwareCompany {
            get {
                return ResourceManager.GetString("SoftwareCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software information.
        /// </summary>
        public static string SoftwareInformation {
            get {
                return ResourceManager.GetString("SoftwareInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software license URL:.
        /// </summary>
        public static string SoftwareLicenseURL {
            get {
                return ResourceManager.GetString("SoftwareLicenseURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A url pointing to txt or rtf document containing the software license..
        /// </summary>
        public static string SoftwareLicenseURLToolTip {
            get {
                return ResourceManager.GetString("SoftwareLicenseURLToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source download location:.
        /// </summary>
        public static string SourceDownloadLocation {
            get {
                return ResourceManager.GetString("SourceDownloadLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The main directory on your server, that contains all of the files needed for the update, it needs to be a valid uri with public read access.
        /// </summary>
        public static string SourceDownloadLocationToolTip {
            get {
                return ResourceManager.GetString("SourceDownloadLocationToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.
        /// </summary>
        public static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seven Update application.
        /// </summary>
        public static string Sua {
            get {
                return ResourceManager.GetString("Sua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seven Update information.
        /// </summary>
        public static string Sui {
            get {
                return ResourceManager.GetString("Sui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support:.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test {0}.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulate updating to detect problems.
        /// </summary>
        public static string TestProjectNote {
            get {
                return ResourceManager.GetString("TestProjectNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestValue.
        /// </summary>
        public static string TestValue {
            get {
                return ResourceManager.GetString("TestValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To get started, right click the list box and add a file or folder of files..
        /// </summary>
        public static string ToGetStartedFiles {
            get {
                return ResourceManager.GetString("ToGetStartedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unregister dll &amp; delete.
        /// </summary>
        public static string UnregisterDelete {
            get {
                return ResourceManager.GetString("UnregisterDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update details:.
        /// </summary>
        public static string UpdateDetails {
            get {
                return ResourceManager.GetString("UpdateDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a summary about the update here, it can be simple as a changelog, but make it no longer than 300 characters.
        /// </summary>
        public static string UpdateDetailsNote {
            get {
                return ResourceManager.GetString("UpdateDetailsNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Optional) http://sevenupdate.com/SDK-Update.
        /// </summary>
        public static string UpdateDetailsUrlNote {
            get {
                return ResourceManager.GetString("UpdateDetailsUrlNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update &amp; execute.
        /// </summary>
        public static string UpdateExecute {
            get {
                return ResourceManager.GetString("UpdateExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update file location:.
        /// </summary>
        public static string UpdateFileLocation {
            get {
                return ResourceManager.GetString("UpdateFileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The url that leads to the SUI file where Seven Update will download and read to determine if your software has updates.
        /// </summary>
        public static string UpdateFileLocationToolTip {
            get {
                return ResourceManager.GetString("UpdateFileLocationToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update if file exists.
        /// </summary>
        public static string UpdateIfFileExists {
            get {
                return ResourceManager.GetString("UpdateIfFileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update importance:.
        /// </summary>
        public static string UpdateImportance {
            get {
                return ResourceManager.GetString("UpdateImportance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorize this update by importance..
        /// </summary>
        public static string UpdateImportanceToolTip {
            get {
                return ResourceManager.GetString("UpdateImportanceToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update information.
        /// </summary>
        public static string UpdateInformation {
            get {
                return ResourceManager.GetString("UpdateInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update information URL:.
        /// </summary>
        public static string UpdateInformationURL {
            get {
                return ResourceManager.GetString("UpdateInformationURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should be a web page with information about this update..
        /// </summary>
        public static string UpdateInformationURLToolTip {
            get {
                return ResourceManager.GetString("UpdateInformationURLToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update name:.
        /// </summary>
        public static string UpdateName {
            get {
                return ResourceManager.GetString("UpdateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance update for MyAppName (max 100 characters).
        /// </summary>
        public static string UpdateNameNote {
            get {
                return ResourceManager.GetString("UpdateNameNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This should describe your update and include the name of the software..
        /// </summary>
        public static string UpdateNameToolTip {
            get {
                return ResourceManager.GetString("UpdateNameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update only.
        /// </summary>
        public static string UpdateOnly {
            get {
                return ResourceManager.GetString("UpdateOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates the shortcut only if it exists on the system.
        /// </summary>
        public static string UpdateOnlyToolTip {
            get {
                return ResourceManager.GetString("UpdateOnlyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update &amp; register dll file.
        /// </summary>
        public static string UpdateRegister {
            get {
                return ResourceManager.GetString("UpdateRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The url you have entered is not valid..
        /// </summary>
        public static string UrlNotValid {
            get {
                return ResourceManager.GetString("UrlNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The url you have entered must point to your sui file..
        /// </summary>
        public static string UrlSui {
            get {
                return ResourceManager.GetString("UrlSui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The url you have entered is valid..
        /// </summary>
        public static string UrlValid {
            get {
                return ResourceManager.GetString("UrlValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid date is required..
        /// </summary>
        public static string ValidDateRequired {
            get {
                return ResourceManager.GetString("ValidDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value data:.
        /// </summary>
        public static string ValueData {
            get {
                return ResourceManager.GetString("ValueData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify data for the value.
        /// </summary>
        public static string ValueDataToolTip {
            get {
                return ResourceManager.GetString("ValueDataToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value name:.
        /// </summary>
        public static string ValueName {
            get {
                return ResourceManager.GetString("ValueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Value Name.
        /// </summary>
        public static string ValueNameNote {
            get {
                return ResourceManager.GetString("ValueNameNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the value that contains the install location of the application.
        /// </summary>
        public static string ValueNameToolTip {
            get {
                return ResourceManager.GetString("ValueNameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Seven Update SDK.
        /// </summary>
        public static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WPFLocalizeExtension is licensed under the.
        /// </summary>
        public static string WPFLocalizeExtensionLicense {
            get {
                return ResourceManager.GetString("WPFLocalizeExtensionLicense", resourceCulture);
            }
        }
    }
}
