//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevenUpdate.WCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCF.IService", CallbackContract=typeof(SevenUpdate.WCF.IServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService/Subscribe")]
        void Subscribe();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService/UnSubscribe")]
        void UnSubscribe();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService/AddApp")]
        void AddApp(SevenUpdate.Base.Sua app);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService/SetUpdates")]
        void SetUpdates(System.Collections.ObjectModel.Collection<SevenUpdate.Base.Sui> appUpdates);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService/ShowUpdate")]
        void ShowUpdate(SevenUpdate.Base.Suh hiddenUpdate);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService/HideUpdate")]
        void HideUpdate(SevenUpdate.Base.Suh hiddenUpdate);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService/HideUpdates")]
        void HideUpdates(System.Collections.ObjectModel.Collection<SevenUpdate.Base.Suh> hiddenUpdates);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService/ChangeSettings")]
        void ChangeSettings(System.Collections.ObjectModel.Collection<SevenUpdate.Base.Sua> apps, SevenUpdate.Base.Config options, bool autoCheck);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService/OnDownloadCompleted")]
        void OnDownloadCompleted(bool errorOccurred);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService/OnInstallCompleted")]
        void OnInstallCompleted(int updatesInstalled, int updatesFailed);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService/OnErrorOccurred")]
        void OnErrorOccurred(string exception, SevenUpdate.Base.ErrorType type);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService/OnDownloadProgressChanged")]
        void OnDownloadProgressChanged(ulong bytesTransferred, ulong bytesTotal, uint filesTransferred, uint filesTotal);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService/OnInstallProgressChanged")]
        void OnInstallProgressChanged(string updateName, int progress, int updatesComplete, int totalUpdates);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : SevenUpdate.WCF.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.DuplexClientBase<SevenUpdate.WCF.IService>, SevenUpdate.WCF.IService {
        
        public ServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Subscribe() {
            base.Channel.Subscribe();
        }
        
        public void UnSubscribe() {
            base.Channel.UnSubscribe();
        }
        
        public void AddApp(SevenUpdate.Base.Sua app) {
            base.Channel.AddApp(app);
        }
        
        public void SetUpdates(System.Collections.ObjectModel.Collection<SevenUpdate.Base.Sui> appUpdates) {
            base.Channel.SetUpdates(appUpdates);
        }
        
        public void ShowUpdate(SevenUpdate.Base.Suh hiddenUpdate) {
            base.Channel.ShowUpdate(hiddenUpdate);
        }
        
        public void HideUpdate(SevenUpdate.Base.Suh hiddenUpdate) {
            base.Channel.HideUpdate(hiddenUpdate);
        }
        
        public void HideUpdates(System.Collections.ObjectModel.Collection<SevenUpdate.Base.Suh> hiddenUpdates) {
            base.Channel.HideUpdates(hiddenUpdates);
        }
        
        public void ChangeSettings(System.Collections.ObjectModel.Collection<SevenUpdate.Base.Sua> apps, SevenUpdate.Base.Config options, bool autoCheck) {
            base.Channel.ChangeSettings(apps, options, autoCheck);
        }
    }
}
