//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevenUpdate.Properties {
    using System;
    
    
    /// <summary>A strongly-typed resource class, for looking up localized strings, etc.</summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>Returns the cached ResourceManager instance used by this class.</summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SevenUpdate.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>Looks up a localized string similar to About Seven Update.</summary>
        public static string AboutSevenUpdate {
            get {
                return ResourceManager.GetString("AboutSevenUpdate", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Read and accept the license terms for.</summary>
        public static string AcceptLicenseTerms {
            get {
                return ResourceManager.GetString("AcceptLicenseTerms", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Accept the terms.</summary>
        public static string AcceptTerms {
            get {
                return ResourceManager.GetString("AcceptTerms", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Add.</summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Add {0} to Seven Update?.</summary>
        public static string AddToSevenUpdate {
            get {
                return ResourceManager.GetString("AddToSevenUpdate", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to This will allow Seven Update to search, download, and install updates for {0}.</summary>
        public static string AllowUpdates {
            get {
                return ResourceManager.GetString("AllowUpdates", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Seven Update is currently already checking for, downloading, or installing updates..</summary>
        public static string AlreadyUpdating {
            get {
                return ResourceManager.GetString("AlreadyUpdating", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Apache License 2.0.</summary>
        public static string ApacheLicense {
            get {
                return ResourceManager.GetString("ApacheLicense", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Microsoft® Windows® API Code Pack is licensed under the.</summary>
        public static string ApiCodePackLicense {
            get {
                return ResourceManager.GetString("ApiCodePackLicense", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Robert Baker (Seven ALive) - Creator and Lead Developer.</summary>
        public static string AppCreator {
            get {
                return ResourceManager.GetString("AppCreator", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Architecture.</summary>
        public static string Architecture {
            get {
                return ResourceManager.GetString("Architecture", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to BSD license.</summary>
        public static string BSDLicense {
            get {
                return ResourceManager.GetString("BSDLicense", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Cancel.</summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to You have chosen to cancel the installation of updates..</summary>
        public static string CancelInstallation {
            get {
                return ResourceManager.GetString("CancelInstallation", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Change settings.</summary>
        public static string ChangeSettings {
            get {
                return ResourceManager.GetString("ChangeSettings", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Seven Update cannot connect to the internet, check your connection or firewall..</summary>
        public static string CheckConnection {
            get {
                return ResourceManager.GetString("CheckConnection", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Check for updates.</summary>
        public static string CheckForUpdates {
            get {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Check for updates for your installed software.</summary>
        public static string CheckForUpdatesHeading {
            get {
                return ResourceManager.GetString("CheckForUpdatesHeading", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Checking for updates....</summary>
        public static string CheckingForUpdates {
            get {
                return ResourceManager.GetString("CheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Check for updates but let me choose to download and install them.</summary>
        public static string CheckUpdatesButChooseToDownload {
            get {
                return ResourceManager.GetString("CheckUpdatesButChooseToDownload", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Choose how Seven Update can install updates.</summary>
        public static string ChooseHowToInstall {
            get {
                return ResourceManager.GetString("ChooseHowToInstall", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Close.</summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Connecting to the Seven Update service....</summary>
        public static string ConnectingToService {
            get {
                return ResourceManager.GetString("ConnectingToService", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Could not connect to the Seven Update server.</summary>
        public static string CouldNotConnect {
            get {
                return ResourceManager.GetString("CouldNotConnect", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Could not connect to the Seven Update service.</summary>
        public static string CouldNotConnectService {
            get {
                return ResourceManager.GetString("CouldNotConnectService", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Could not connect to the Seven Update service.</summary>
        public static string CouldNotConnectToService {
            get {
                return ResourceManager.GetString("CouldNotConnectToService", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Date Installed.</summary>
        public static string DateInstalled {
            get {
                return ResourceManager.GetString("DateInstalled", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Decline.</summary>
        public static string Decline {
            get {
                return ResourceManager.GetString("Decline", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Development Team:.</summary>
        public static string DevelopmentTeam {
            get {
                return ResourceManager.GetString("DevelopmentTeam", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Download and install your selected updates.</summary>
        public static string DownloadAndInstallUpdates {
            get {
                return ResourceManager.GetString("DownloadAndInstallUpdates", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Downloading License Agreement, please wait....</summary>
        public static string DownloadingLicenseAgreement {
            get {
                return ResourceManager.GetString("DownloadingLicenseAgreement", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Downloading Updates....</summary>
        public static string DownloadingUpdates {
            get {
                return ResourceManager.GetString("DownloadingUpdates", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Downloading updates... ({0}, {1}% complete).</summary>
        public static string DownloadPercentProgress {
            get {
                return ResourceManager.GetString("DownloadPercentProgress", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Downloading updates... ({0} out of {1} files).</summary>
        public static string DownloadProgress {
            get {
                return ResourceManager.GetString("DownloadProgress", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Download size: {0}.</summary>
        public static string DownloadSize {
            get {
                return ResourceManager.GetString("DownloadSize", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Download updates but let me choose to install them (recommended).</summary>
        public static string DownloadUpdatesButChooseToInstall {
            get {
                return ResourceManager.GetString("DownloadUpdatesButChooseToInstall", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to An error occurred while searching, downloading, or installing updates..</summary>
        public static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Failed.</summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Finish.</summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Give me recommended updates the same way I receive important updates.</summary>
        public static string GiveRecommendedUpdates {
            get {
                return ResourceManager.GetString("GiveRecommendedUpdates", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Help and support.</summary>
        public static string HelpSupport {
            get {
                return ResourceManager.GetString("HelpSupport", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Hidden.</summary>
        public static string Hidden {
            get {
                return ResourceManager.GetString("Hidden", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Hide update.</summary>
        public static string HideUpdate {
            get {
                return ResourceManager.GetString("HideUpdate", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Importance.</summary>
        public static string Importance {
            get {
                return ResourceManager.GetString("Importance", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Important.</summary>
        public static string Important {
            get {
                return ResourceManager.GetString("Important", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to 1 important update available.</summary>
        public static string ImportantUpdateAvailable {
            get {
                return ResourceManager.GetString("ImportantUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Important updates.</summary>
        public static string ImportantUpdates {
            get {
                return ResourceManager.GetString("ImportantUpdates", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to {0} important updates are available.</summary>
        public static string ImportantUpdatesAvailable {
            get {
                return ResourceManager.GetString("ImportantUpdatesAvailable", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to 1 important update selected.</summary>
        public static string ImportantUpdateSelected {
            get {
                return ResourceManager.GetString("ImportantUpdateSelected", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to {0} important updates selected.</summary>
        public static string ImportantUpdatesSelected {
            get {
                return ResourceManager.GetString("ImportantUpdatesSelected", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Installation status: {0}, installed on {1}.</summary>
        public static string InstallationStatus {
            get {
                return ResourceManager.GetString("InstallationStatus", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Installing {0} {1} out of {2}, {3}% complete.</summary>
        public static string InstallExtendedProgress {
            get {
                return ResourceManager.GetString("InstallExtendedProgress", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Installing updates....</summary>
        public static string InstallingUpdates {
            get {
                return ResourceManager.GetString("InstallingUpdates", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Always install the latest updates to enhance your software security and performance..</summary>
        public static string InstallLatestUpdates {
            get {
                return ResourceManager.GetString("InstallLatestUpdates", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Installing {0} {1}% complete.</summary>
        public static string InstallProgress {
            get {
                return ResourceManager.GetString("InstallProgress", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Install updates.</summary>
        public static string InstallUpdates {
            get {
                return ResourceManager.GetString("InstallUpdates", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Install updates automatically.</summary>
        public static string InstallUpdatesAutomatically {
            get {
                return ResourceManager.GetString("InstallUpdatesAutomatically", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Install updates for your programs.</summary>
        public static string InstallUpdatesForPrograms {
            get {
                return ResourceManager.GetString("InstallUpdatesForPrograms", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Error Downloading License Agreement.</summary>
        public static string LicenseDownloadError {
            get {
                return ResourceManager.GetString("LicenseDownloadError", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Locale.</summary>
        public static string Locale {
            get {
                return ResourceManager.GetString("Locale", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Microsoft Software License.</summary>
        public static string MicrosoftLicense {
            get {
                return ResourceManager.GetString("MicrosoftLicense", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Microsoft Public License.</summary>
        public static string MicrosoftPublicLicense {
            get {
                return ResourceManager.GetString("MicrosoftPublicLicense", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to More information.</summary>
        public static string MoreInformation {
            get {
                return ResourceManager.GetString("MoreInformation", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Name.</summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Never.</summary>
        public static string Never {
            get {
                return ResourceManager.GetString("Never", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Never check for updates (not recommended).</summary>
        public static string NeverCheckForUpdates {
            get {
                return ResourceManager.GetString("NeverCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Next.</summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to No important updates available.</summary>
        public static string NoImportantUpdates {
            get {
                return ResourceManager.GetString("NoImportantUpdates", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to No new updates are available for your programs..</summary>
        public static string NoNewUpdates {
            get {
                return ResourceManager.GetString("NoNewUpdates", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Not Available.</summary>
        public static string NotAvailable {
            get {
                return ResourceManager.GetString("NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to No updates are available for your programs..</summary>
        public static string NoUpdates {
            get {
                return ResourceManager.GetString("NoUpdates", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to No updates are currently selected..</summary>
        public static string NoUpdatesSelected {
            get {
                return ResourceManager.GetString("NoUpdatesSelected", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to _OK.</summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Optional.</summary>
        public static string Optional {
            get {
                return ResourceManager.GetString("Optional", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to 1 optional update available.</summary>
        public static string OptionalUpdateAvailable {
            get {
                return ResourceManager.GetString("OptionalUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to {0} optional update are available.</summary>
        public static string OptionalUpdatesAvailable {
            get {
                return ResourceManager.GetString("OptionalUpdatesAvailable", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to 1 optional update selected.</summary>
        public static string OptionalUpdateSelected {
            get {
                return ResourceManager.GetString("OptionalUpdateSelected", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to {0} optional updates selected.</summary>
        public static string OptionalUpdatesSelected {
            get {
                return ResourceManager.GetString("OptionalUpdatesSelected", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to When your computer is online, Seven Update can automatically check for updates and download them using these settings..</summary>
        public static string OptionDescription {
            get {
                return ResourceManager.GetString("OptionDescription", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Options.</summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Please wait, downloading the program list....</summary>
        public static string PleaseWaitDownloading {
            get {
                return ResourceManager.GetString("PleaseWaitDownloading", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Portions of code use the following libraries:.</summary>
        public static string PortionsOfCode {
            get {
                return ResourceManager.GetString("PortionsOfCode", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Preparing to download updates....</summary>
        public static string PreparingDownload {
            get {
                return ResourceManager.GetString("PreparingDownload", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Preparing to install updates....</summary>
        public static string PreparingInstall {
            get {
                return ResourceManager.GetString("PreparingInstall", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Program.</summary>
        public static string Program {
            get {
                return ResourceManager.GetString("Program", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Your programs are up to date.</summary>
        public static string ProgramsUpToDate {
            get {
                return ResourceManager.GetString("ProgramsUpToDate", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to protobuf-net is licensed under the.</summary>
        public static string protobufLicense {
            get {
                return ResourceManager.GetString("protobufLicense", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Published:.</summary>
        public static string Published {
            get {
                return ResourceManager.GetString("Published", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Publisher.</summary>
        public static string Publisher {
            get {
                return ResourceManager.GetString("Publisher", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Ready to download.</summary>
        public static string ReadyToDownload {
            get {
                return ResourceManager.GetString("ReadyToDownload", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Ready to install.</summary>
        public static string ReadyToInstall {
            get {
                return ResourceManager.GetString("ReadyToInstall", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Would you like to reboot your computer?.</summary>
        public static string RebootComputer {
            get {
                return ResourceManager.GetString("RebootComputer", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Your computer needs to be restarted to finish updates..</summary>
        public static string RebootNeeded {
            get {
                return ResourceManager.GetString("RebootNeeded", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Seven Update cannot currently check for updates, because you must first restart the computer so that a previous installation may be completed..</summary>
        public static string RebootNeededFirst {
            get {
                return ResourceManager.GetString("RebootNeededFirst", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Most recent check for updates:.</summary>
        public static string RecentCheck {
            get {
                return ResourceManager.GetString("RecentCheck", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Updates were installed:.</summary>
        public static string RecentInstall {
            get {
                return ResourceManager.GetString("RecentInstall", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Recommended.</summary>
        public static string Recommended {
            get {
                return ResourceManager.GetString("Recommended", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Restart now.</summary>
        public static string RestartNow {
            get {
                return ResourceManager.GetString("RestartNow", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Restore.</summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Restore hidden updates.</summary>
        public static string RestoreHiddenUpdates {
            get {
                return ResourceManager.GetString("RestoreHiddenUpdates", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Review your update history.</summary>
        public static string ReviewUpdateHistory {
            get {
                return ResourceManager.GetString("ReviewUpdateHistory", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Save.</summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Save your work and reboot your machine to complete the installation of updates..</summary>
        public static string SaveAndReboot {
            get {
                return ResourceManager.GetString("SaveAndReboot", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Select the programs that will be updated with Seven Update..</summary>
        public static string SelectPrograms {
            get {
                return ResourceManager.GetString("SelectPrograms", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Select the updates you want to install.</summary>
        public static string SelectUpdatesToInstall {
            get {
                return ResourceManager.GetString("SelectUpdatesToInstall", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Seven Update.</summary>
        public static string SevenUpdate {
            get {
                return ResourceManager.GetString("SevenUpdate", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Seven Update is licensed under the GNU GPL 3.0 © 2007-2010.</summary>
        public static string SevenUpdateLicense {
            get {
                return ResourceManager.GetString("SevenUpdateLicense", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to SharpBITS.NET is licensed under the.</summary>
        public static string SharpBitsLicense {
            get {
                return ResourceManager.GetString("SharpBitsLicense", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Show update.</summary>
        public static string ShowUpdate {
            get {
                return ResourceManager.GetString("ShowUpdate", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Size.</summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Software License Agreement.</summary>
        public static string SoftwareLicenseAgreement {
            get {
                return ResourceManager.GetString("SoftwareLicenseAgreement", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Status.</summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Stop download.</summary>
        public static string StopDownload {
            get {
                return ResourceManager.GetString("StopDownload", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Stop installation.</summary>
        public static string StopInstallation {
            get {
                return ResourceManager.GetString("StopInstallation", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Successful.</summary>
        public static string Successful {
            get {
                return ResourceManager.GetString("Successful", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Support:.</summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Tasks.</summary>
        public static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to {0} at {1}.</summary>
        public static string TimeAt {
            get {
                return ResourceManager.GetString("TimeAt", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Today at {0}.</summary>
        public static string TodayAt {
            get {
                return ResourceManager.GetString("TodayAt", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Total selected: {0} updates.</summary>
        public static string TotalSelectedUpdates {
            get {
                return ResourceManager.GetString("TotalSelectedUpdates", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Try Again.</summary>
        public static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to An unknown error occurred.</summary>
        public static string UnknownErrorOccurred {
            get {
                return ResourceManager.GetString("UnknownErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to 1 update failed.</summary>
        public static string UpdateFailed {
            get {
                return ResourceManager.GetString("UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Update History.</summary>
        public static string UpdateHistory {
            get {
                return ResourceManager.GetString("UpdateHistory", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Update Information.</summary>
        public static string UpdateInformation {
            get {
                return ResourceManager.GetString("UpdateInformation", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to 1 update succeeded.</summary>
        public static string UpdateInstalled {
            get {
                return ResourceManager.GetString("UpdateInstalled", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Updates have been canceled.</summary>
        public static string UpdatesCanceled {
            get {
                return ResourceManager.GetString("UpdatesCanceled", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to {0} updates failed.</summary>
        public static string UpdatesFailed {
            get {
                return ResourceManager.GetString("UpdatesFailed", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to {0} updates succeeded.</summary>
        public static string UpdatesInstalled {
            get {
                return ResourceManager.GetString("UpdatesInstalled", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to {0} succeeded, {1} failed.</summary>
        public static string UpdatesInstalledFailed {
            get {
                return ResourceManager.GetString("UpdatesInstalledFailed", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to The updates were successfully installed.</summary>
        public static string UpdatesInstalledTitle {
            get {
                return ResourceManager.GetString("UpdatesInstalledTitle", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Updates are ready to be installed.</summary>
        public static string UpdatesReadyInstalled {
            get {
                return ResourceManager.GetString("UpdatesReadyInstalled", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Update type:.</summary>
        public static string UpdateType {
            get {
                return ResourceManager.GetString("UpdateType", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to Version:.</summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to View Details.</summary>
        public static string ViewDetails {
            get {
                return ResourceManager.GetString("ViewDetails", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to View important updates.</summary>
        public static string ViewImportantUpdates {
            get {
                return ResourceManager.GetString("ViewImportantUpdates", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to View optional updates.</summary>
        public static string ViewOptionalUpdates {
            get {
                return ResourceManager.GetString("ViewOptionalUpdates", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to View update history.</summary>
        public static string ViewUpdateHistory {
            get {
                return ResourceManager.GetString("ViewUpdateHistory", resourceCulture);
            }
        }
        
        /// <summary>Looks up a localized string similar to WPFLocalizeExtension is licensed under the.</summary>
        public static string WPFLocalizeExtensionLicense {
            get {
                return ResourceManager.GetString("WPFLocalizeExtensionLicense", resourceCulture);
            }
        }
    }
}
