//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevenUpdate.Sdk.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UIStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SevenUpdate.Sdk.Resources.UIStrings", typeof(UIStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating hash.
        /// </summary>
        internal static string CalculatingHash {
            get {
                return ResourceManager.GetString("CalculatingHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix all errors to continue.
        /// </summary>
        internal static string CorrectErrors {
            get {
                return ResourceManager.GetString("CorrectErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t show me this message again..
        /// </summary>
        internal static string DontShowMessage {
            get {
                return ResourceManager.GetString("DontShowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exclamation mark next to a value denotes an error..
        /// </summary>
        internal static string ErrorHelp {
            get {
                return ResourceManager.GetString("ErrorHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you would like to exit?.
        /// </summary>
        internal static string ExitConfirm {
            get {
                return ResourceManager.GetString("ExitConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you exit now you will lose unsaved progress..
        /// </summary>
        internal static string LoseProgress {
            get {
                return ResourceManager.GetString("LoseProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Registry Item.
        /// </summary>
        internal static string NewRegistryItem {
            get {
                return ResourceManager.GetString("NewRegistryItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Shortcut.
        /// </summary>
        internal static string NewShortcut {
            get {
                return ResourceManager.GetString("NewShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry Item.
        /// </summary>
        internal static string RegistryItem {
            get {
                return ResourceManager.GetString("RegistryItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seven Software.
        /// </summary>
        internal static string SevenSoftware {
            get {
                return ResourceManager.GetString("SevenSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seven Update SDK.
        /// </summary>
        internal static string SevenUpdateSDK {
            get {
                return ResourceManager.GetString("SevenUpdateSDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut.
        /// </summary>
        internal static string Shortcut {
            get {
                return ResourceManager.GetString("Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The url you have entered is not valid..
        /// </summary>
        internal static string UrlNotValid {
            get {
                return ResourceManager.GetString("UrlNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The url you have entered must point to your sui file..
        /// </summary>
        internal static string UrlSui {
            get {
                return ResourceManager.GetString("UrlSui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The url you have entered is valid..
        /// </summary>
        internal static string UrlValid {
            get {
                return ResourceManager.GetString("UrlValid", resourceCulture);
            }
        }
    }
}
