//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.20506.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevenUpdate.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SevenUpdate.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please read and accept the license terms for.
        /// </summary>
        internal static string AcceptLicenseTerms {
            get {
                return ResourceManager.GetString("AcceptLicenseTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to allow Seven Update to search, download and install updates for.
        /// </summary>
        internal static string AllowUpdates {
            get {
                return ResourceManager.GetString("AllowUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seven Update is currently already checking for, downloading, or installing updates..
        /// </summary>
        internal static string AlreadyUpdating {
            get {
                return ResourceManager.GetString("AlreadyUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at.
        /// </summary>
        internal static string At {
            get {
                return ResourceManager.GetString("At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have chosen to cancel the installation of updates..
        /// </summary>
        internal static string CancelInstallation {
            get {
                return ResourceManager.GetString("CancelInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel updates.
        /// </summary>
        internal static string CancelUpdates {
            get {
                return ResourceManager.GetString("CancelUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seven Update cannot connect to the internet, please check your connection or firewall..
        /// </summary>
        internal static string CheckConnection {
            get {
                return ResourceManager.GetString("CheckConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates.
        /// </summary>
        internal static string CheckingForUpdates {
            get {
                return ResourceManager.GetString("CheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates but let me choose whether to download and install them.
        /// </summary>
        internal static string CheckUpdatesOnly {
            get {
                return ResourceManager.GetString("CheckUpdatesOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to complete.
        /// </summary>
        internal static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seven Update has completed installing updates..
        /// </summary>
        internal static string CompletedInstallingUpdates {
            get {
                return ResourceManager.GetString("CompletedInstallingUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to the Seven Update server.
        /// </summary>
        internal static string CouldNotConnect {
            get {
                return ResourceManager.GetString("CouldNotConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download and install updates for your programs.
        /// </summary>
        internal static string DownloadAndInstallUpdates {
            get {
                return ResourceManager.GetString("DownloadAndInstallUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Updates.
        /// </summary>
        internal static string DownloadingUpdates {
            get {
                return ResourceManager.GetString("DownloadingUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seven Update is downloading updates in the background..
        /// </summary>
        internal static string DownloadingUpdatesBackground {
            get {
                return ResourceManager.GetString("DownloadingUpdatesBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download updates but let me choose whether to install them (Recommended).
        /// </summary>
        internal static string DownloadUpdatesOnly {
            get {
                return ResourceManager.GetString("DownloadUpdatesOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while searching, downloading, or installing updates.
        /// </summary>
        internal static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you would like to exit?.
        /// </summary>
        internal static string ExitConfirm {
            get {
                return ResourceManager.GetString("ExitConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seven Update has finish downloading updates, click here to view them..
        /// </summary>
        internal static string FinishedDownloading {
            get {
                return ResourceManager.GetString("FinishedDownloading", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap greenShield {
            get {
                object obj = ResourceManager.GetObject("greenShield", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap greenSide {
            get {
                object obj = ResourceManager.GetObject("greenSide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        internal static string Hidden {
            get {
                return ResourceManager.GetString("Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide update.
        /// </summary>
        internal static string HideUpdate {
            get {
                return ResourceManager.GetString("HideUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to important update available.
        /// </summary>
        internal static string ImportantUpdateAvaliable {
            get {
                return ResourceManager.GetString("ImportantUpdateAvaliable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to important updates are available.
        /// </summary>
        internal static string ImportantUpdatesAvaliable {
            get {
                return ResourceManager.GetString("ImportantUpdatesAvaliable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to important update selected.
        /// </summary>
        internal static string ImportantUpdateSelected {
            get {
                return ResourceManager.GetString("ImportantUpdateSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to important updates selected.
        /// </summary>
        internal static string ImportantUpdatesSelected {
            get {
                return ResourceManager.GetString("ImportantUpdatesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing.
        /// </summary>
        internal static string Installing {
            get {
                return ResourceManager.GetString("Installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing updates.
        /// </summary>
        internal static string InstallingUpdates {
            get {
                return ResourceManager.GetString("InstallingUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seven Update is installing updates in the background..
        /// </summary>
        internal static string InstallingUpdatesBackground {
            get {
                return ResourceManager.GetString("InstallingUpdatesBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install updates.
        /// </summary>
        internal static string InstallUpdates {
            get {
                return ResourceManager.GetString("InstallUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install updates automatically.
        /// </summary>
        internal static string InstallUpdatesAutomatically {
            get {
                return ResourceManager.GetString("InstallUpdatesAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last updated:.
        /// </summary>
        internal static string LastUpdated {
            get {
                return ResourceManager.GetString("LastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never check for updates (not recommended).
        /// </summary>
        internal static string NeverCheckUpdates {
            get {
                return ResourceManager.GetString("NeverCheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No important updates available.
        /// </summary>
        internal static string NoImportantUpdates {
            get {
                return ResourceManager.GetString("NoImportantUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No new updates are available for your programs..
        /// </summary>
        internal static string NoNewUpdates {
            get {
                return ResourceManager.GetString("NoNewUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No updates are currently selected..
        /// </summary>
        internal static string NoUpdatesSelected {
            get {
                return ResourceManager.GetString("NoUpdatesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to optional update available.
        /// </summary>
        internal static string OptionalUpdateAvaliable {
            get {
                return ResourceManager.GetString("OptionalUpdateAvaliable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to optional update are available.
        /// </summary>
        internal static string OptionalUpdatesAvaliable {
            get {
                return ResourceManager.GetString("OptionalUpdatesAvaliable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to optional update selected.
        /// </summary>
        internal static string OptionalUpdateSelected {
            get {
                return ResourceManager.GetString("OptionalUpdateSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to optional updates selected.
        /// </summary>
        internal static string OptionalUpdatesSelected {
            get {
                return ResourceManager.GetString("OptionalUpdatesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to out of.
        /// </summary>
        internal static string OutOf {
            get {
                return ResourceManager.GetString("OutOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing to download updates....
        /// </summary>
        internal static string PreparingDownload {
            get {
                return ResourceManager.GetString("PreparingDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing to install updates....
        /// </summary>
        internal static string PreparingInstall {
            get {
                return ResourceManager.GetString("PreparingInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your programs are up to date.
        /// </summary>
        internal static string ProgramsUpToDate {
            get {
                return ResourceManager.GetString("ProgramsUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to download.
        /// </summary>
        internal static string ReadyToDownload {
            get {
                return ResourceManager.GetString("ReadyToDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to install.
        /// </summary>
        internal static string ReadyToInstall {
            get {
                return ResourceManager.GetString("ReadyToInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your computer needs to be restarted to finish updates..
        /// </summary>
        internal static string RebootNeeded {
            get {
                return ResourceManager.GetString("RebootNeeded", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap redShield {
            get {
                object obj = ResourceManager.GetObject("redShield", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap redSide {
            get {
                object obj = ResourceManager.GetObject("redSide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart now.
        /// </summary>
        internal static string RestartNow {
            get {
                return ResourceManager.GetString("RestartNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please save your work and reboot your machine to complete the installation of updates..
        /// </summary>
        internal static string SaveAndReboot {
            get {
                return ResourceManager.GetString("SaveAndReboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seven Software.
        /// </summary>
        internal static string SevenSoftware {
            get {
                return ResourceManager.GetString("SevenSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seven Update.
        /// </summary>
        internal static string SevenUpdate {
            get {
                return ResourceManager.GetString("SevenUpdate", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap shield {
            get {
                object obj = ResourceManager.GetObject("shield", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show update.
        /// </summary>
        internal static string ShowUpdate {
            get {
                return ResourceManager.GetString("ShowUpdate", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap sidebar {
            get {
                object obj = ResourceManager.GetObject("sidebar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sidebar2 {
            get {
                object obj = ResourceManager.GetObject("sidebar2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap smallGreenShield {
            get {
                object obj = ResourceManager.GetObject("smallGreenShield", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap smallRedShield {
            get {
                object obj = ResourceManager.GetObject("smallRedShield", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succeeded.
        /// </summary>
        internal static string Succeeded {
            get {
                return ResourceManager.GetString("Succeeded", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap SUIcon {
            get {
                object obj = ResourceManager.GetObject("SUIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today at.
        /// </summary>
        internal static string TodayAt {
            get {
                return ResourceManager.GetString("TodayAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total selected:.
        /// </summary>
        internal static string TotalSelected {
            get {
                return ResourceManager.GetString("TotalSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try Again.
        /// </summary>
        internal static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred.
        /// </summary>
        internal static string UnknownErrorOccurred {
            get {
                return ResourceManager.GetString("UnknownErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updates.
        /// </summary>
        internal static string Updates {
            get {
                return ResourceManager.GetString("Updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are updates available, click here to see them.
        /// </summary>
        internal static string UpdatesAvailable {
            get {
                return ResourceManager.GetString("UpdatesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates have been canceled.
        /// </summary>
        internal static string UpdatesCanceled {
            get {
                return ResourceManager.GetString("UpdatesCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates are complete.
        /// </summary>
        internal static string UpdatesComplete {
            get {
                return ResourceManager.GetString("UpdatesComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates have been downloaded.
        /// </summary>
        internal static string UpdatesDownloaded {
            get {
                return ResourceManager.GetString("UpdatesDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update selected.
        /// </summary>
        internal static string UpdateSelected {
            get {
                return ResourceManager.GetString("UpdateSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates are ready to be installed.
        /// </summary>
        internal static string UpdatesReadyInstalled {
            get {
                return ResourceManager.GetString("UpdatesReadyInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seven Update is currently installing updates. It is highly recommended that you wait until installation is finished. If you would like to still exit, the installation will be aborted and then Seven Update will close..
        /// </summary>
        internal static string WarnOnExit {
            get {
                return ResourceManager.GetString("WarnOnExit", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap yellowShield {
            get {
                object obj = ResourceManager.GetObject("yellowShield", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap yellowSide {
            get {
                object obj = ResourceManager.GetObject("yellowSide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
